# Generated by Django 6.0.7 on 2026-07-30 17:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(default='fa-taxi', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('client', 'Mijoz'), ('driver', 'Haydovchi'), ('dispatcher', 'Dispetcher'), ('admin', 'Admin')], default='client', max_length=20)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('license_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('tech_passport_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Tasdiqlanmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('blocked', 'Bloklangan')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('taxi', 'Taksi'), ('delivery', 'Yetkazib berish')], default='taxi', max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('searching', 'Haydovchi qidirilmoqda'), ('accepted', 'Qabul qilindi'), ('arrived', 'Haydovchi yetib keldi'), ('in_progress', "Yo'lda"), ('completed', 'Yakunlandi'), ('cancelled_by_client', 'Mijoz tomonidan bekor qilindi'), ('cancelled_by_driver', 'Haydovchi tomonidan bekor qilindi')], default='searching', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.driver')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_rating_for_driver', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_rating_for_client', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_data', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=20)),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('none', '—')], default='none', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'landi"), ('failed', 'Xato')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_size', models.CharField(choices=[('small', 'Kichik (xat, hujjat)'), ('medium', "O'rta (quti, maishiy buyum)"), ('large', "Katta (yirik jo'natma)")], default='small', max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='core.trip')),
            ],
        ),
    ]
